var message={
    DATA_FOUND:'Data Found.',
    DATA_NOT_FOUND:'Data not found.',
    LOGOUT_SUCCESS:'Logout successfully.',
    INVALID_DATA:'Invalid data.',
    INVALID_LENGTH:'Length of {} should be of {} to {} characters.',
    SERVER_ERROR:'Server error.',
    DATA_SAVED:'Data Saved.',
    DATA_NOT_SAVED:'Data not saved.',
    EMPTY_FIELD_EMAIL:'Please type email.',
    EMPTY_FIELD_PASS:'Please Type Password.',
    EMPTY_FIELD_FIRST:'Please Type first name.',
    EMPTY_FIELD_LAST:'Please Type last name.',
    EMPTY_FIELD_PHONE:'Please Type phone.',
    EMPTY_FIELD_OTP:'Please Type 4 digit OTP.',
    INVALID_OTP:'Invalid 4 digit OTP.',
    ACTIVATION:'User is not activated.',
    EMAIL_REGISTERED:'Email is already registered.',
    REGISTERED_USER:'User registered please check your email and activate your account.',
    ACTIVATED_USER:'User is activated you can login to your account.',
    INVALID_TOKEN:'Invalid session token.',
    CHANGE_PASS:'Password reset successful.',
};

module.exports=message;